// src/components/back-to-top.svelte
<script>
	import { fly } from 'svelte/transition'

	export let showThreshold = 150

	let show = false

	function container() {
		return document.documentElement || document.body
	}

	function handleScroll() {
		if (!container()) {
			return
		}

		show = container().scrollTop > showThreshold ? true : false
	}

	function backToTop() {
		document.body.scrollIntoView()
	}
</script>

<svelte:window on:scroll={handleScroll} />

<div
	class="fixed z-50 hidden md:block pointer-events-none p-4 mb-4 bottom-0 right-0 left-0 max-w-6xl mx-auto"
>
	{#if show}
		<button
			class="text-6xl bg-button-active outline outline-highlight-hover absolute right-0 bottom-0 rounded-md hover:bg-button-hover mr-4 pointer-events-auto"
			on:click={backToTop}
			transition:fly={{ y: 100, duration: 150 }}
		>
			<span class="sr-only">Scroll To Top</span>
			<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
				<path fill="currentColor" d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6l-6 6z" />
			</svg>
		</button>
	{/if}
</div>

// src/components/back-to-top.tsx
import { useEffect, useState } from 'react'

export function BackToTop({ showThreshold = 150 }: { showThreshold?: number }) {
  const [show, setShow] = useState(false)
  useEffect(() => {
    const onScroll = () => setShow(document.documentElement.scrollTop > showThreshold)
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [showThreshold])
  return <div className="pointer-events-none fixed inset-x-0 bottom-0 z-50 mx-auto mb-4 hidden max-w-6xl p-4 md:block">{show && <button className="back-to-top-enter pointer-events-auto absolute bottom-0 right-0 mr-4 rounded-md bg-site-button-active text-6xl outline outline-site-border-hover hover:bg-site-button-hover" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><span className="sr-only">Scroll To Top</span><svg width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6l-6 6z" /></svg></button>}</div>
}
