// src/components/button.svelte
<script lang="ts">
	export let onclick: () => void | ((e: Event) => void) | Promise<void> | void
	export let classes = ''
</script>

<button
	class={`rounded-md bg-button p-1 px-2 font-semibold text-button-text-active flex gap-2 items-center font-heading tracking-wide active:scale-105 transition-all duration-100 ease-springy hover:outline outline-highlight-hover outline-2 active:outline hover:bg-button-hover  ${classes}`}
	on:click={onclick}
	{...$$restProps}
>
	<slot />
</button>

// src/components/button.tsx
import type { ButtonHTMLAttributes } from 'react'
import { cn } from '@/lib/utils'

export function Button({ className, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) {
  return <button className={cn('flex items-center gap-2 rounded-md bg-site-button px-2 py-1 font-site-heading font-semibold tracking-wide text-site-active-foreground outline-2 outline-site-border-hover transition-all duration-100 ease-springy hover:bg-site-button-hover hover:outline active:scale-105 active:outline', className)} {...props} />
}
