// src/components/status-card.tsx
import { useEffect, useState } from 'react'
import { useLanyard } from 'use-lanyard'
import { Icon } from './icon'

const discordId = '394953409855488012'

export function StatusCard() {
  const data = useLanyard(discordId)
  const [, tick] = useState(0)
  useEffect(() => {
    const timer = window.setInterval(() => tick((value) => value + 1), 1000)
    return () => window.clearInterval(timer)
  }, [])

  const activity = data?.activities?.[0]
  const spotify = data?.spotify
  const elapsed = spotify ? Math.max(0, Date.now() - spotify.timestamps.start) : 0
  const duration = spotify ? spotify.timestamps.end - spotify.timestamps.start : 1
  const progress = Math.min(100, (elapsed / duration) * 100)
  const minutes = Math.floor(elapsed / 60000)
  const seconds = String(Math.floor((elapsed / 1000) % 60)).padStart(2, '0')
  const statusColor = data?.discord_status === 'online' ? 'bg-green-500' : data?.discord_status === 'idle' ? 'bg-yellow-500' : 'bg-red-500'
  const title = spotify ? 'Listening to Spotify' : activity ? 'Playing' : 'Thinking...'

  return (
    <section className="overflow-hidden p-1">
      <header className="flex items-center gap-2 text-sm md:mb-1 md:border-b md:border-site-border md:pb-1">
        {spotify && <Icon name="mdi:spotify" className="text-green-500" />}
        {!spotify && activity && <Icon name="mdi:gamepad-variant" className="text-site-icon-hover" />}
        {!activity && !spotify && <span className={`h-2 w-2 animate-bounce rounded-full ${statusColor}`} />}
        <span className="font-mono">{title}</span>
      </header>
      {spotify && <section className="flex items-center gap-2 pb-2 text-sm md:block md:px-1 md:p-2">
        <a href={`spotify:track:${spotify.track_id}`} className="flex items-center gap-2 md:block"><span className="block overflow-hidden text-ellipsis whitespace-nowrap font-bold">{spotify.song}</span><span className="block overflow-hidden text-ellipsis whitespace-nowrap">by <span className="font-bold">{spotify.artist}</span></span></a>
        <div className="mt-2 hidden h-2 overflow-hidden rounded-md bg-site-spotify-track md:block"><div className="h-full bg-site-spotify-progress transition-[width] duration-75" style={{ width: `${progress}%` }} /></div>
        <time className="hidden md:block">{minutes}:{seconds}</time>
      </section>}
      {!spotify && activity && <section><span className="font-semibold text-site-heading">{activity.name}</span>{activity.state && <div><span>Currently: </span><span className="font-semibold">{activity.state}</span></div>}</section>}
    </section>
  )
}

// src/components/StatusCard.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { useLanyard } from 'svelte-lanyard'
	import { fade } from 'svelte/transition'

	let data: ReturnType<typeof useLanyard>

	let currentTimestamp: number = Date.now()
	let startTimestamp: number = 0
	let endTimestamp: number = 0
	let currentMinutes: number = 0
	let currentSeconds: number = 0
	let intervalRate: number = 1000
	let clear: ReturnType<typeof setInterval>
	let progress = 0

	onMount(async () => {
		data = useLanyard('394953409855488012')
	})

	// For Progress Bar
	function updateTimestamps(spotify_data: typeof $data) {
		if (spotify_data) {
			currentTimestamp = Date.now()
			startTimestamp = spotify_data.spotify?.timestamps.start!
			endTimestamp = spotify_data.spotify?.timestamps.end!
			let totalDuration = endTimestamp - startTimestamp
			let elapsedDuration = currentTimestamp - startTimestamp
			progress = (elapsedDuration / totalDuration) * 100

			let differenceInMilliseconds = currentTimestamp - startTimestamp!
			currentMinutes = Math.floor(differenceInMilliseconds / (1000 * 60)) // Convert milliseconds to minutes

			currentSeconds = Math.floor((differenceInMilliseconds / 1000) % 60)
		}
	}

	$: {
		clearInterval(clear)
		clear = setInterval(() => updateTimestamps($data), intervalRate)
	}

	$: formattedSeconds = currentSeconds < 10 ? '0' + currentSeconds : currentSeconds
</script>

{#if $data}
	{#if $data.listening_to_spotify}
		<section class="md:block hidden p-2 px-1 text-sm" transition:fade>
			<span class="block font-mono font-semibold pb-1 border-b border-b-highlight mb-4"
				>Listening to Spotify</span
			>
			<a href={`spotify:track:${$data.spotify?.track_id}`}>
				<div class="">
					<section>
						<span class="block text-ellipsis overflow-hidden whitespace-nowrap font-bold"
							>{$data.spotify?.song}</span
						>
						<span class="block text-ellipsis overflow-hidden whitespace-nowrap"
							>by <span class="font-bold">{$data.spotify?.artist}</span></span
						>
					</section>
				</div>
			</a>
			<div class="progress-bar h-2 bg-spotify-progress-outer rounded-md overflow-hidden mt-2">
				<div
					class="bg-spotify-progress h-full progress-bar-inner"
					style={`--progress: ${progress}%`}
				></div>
			</div>
			<time>
				{currentMinutes}:{formattedSeconds}
			</time>
		</section>
	{/if}
{/if}

<style>
	.progress-bar-inner {
		width: var(--progress);
	}
</style>
