// src/components/status-card.tsx
import { useEffect, useState } from 'react'
import { useLanyard } from 'use-lanyard'
import { Icon } from './icon'

const discordId = '394953409855488012'

export function StatusCard() {
  const data = useLanyard(discordId)
  const [, tick] = useState(0)
  useEffect(() => {
    const timer = window.setInterval(() => tick((value) => value + 1), 1000)
    return () => window.clearInterval(timer)
  }, [])

  const activity = data?.activities?.[0]
  const spotify = data?.spotify
  const elapsed = spotify ? Math.max(0, Date.now() - spotify.timestamps.start) : 0
  const duration = spotify ? spotify.timestamps.end - spotify.timestamps.start : 1
  const progress = Math.min(100, (elapsed / duration) * 100)
  const minutes = Math.floor(elapsed / 60000)
  const seconds = String(Math.floor((elapsed / 1000) % 60)).padStart(2, '0')
  const statusColor = data?.discord_status === 'online' ? 'bg-green-500' : data?.discord_status === 'idle' ? 'bg-yellow-500' : 'bg-red-500'
  const title = spotify ? 'Listening to Spotify' : activity ? 'Playing' : 'Thinking...'

  return (
    <section className="overflow-hidden p-1">
      <header className="flex items-center gap-2 text-sm md:mb-1 md:border-b md:border-site-border md:pb-1">
        {spotify && <Icon name="mdi:spotify" className="text-green-500" />}
        {!spotify && activity && <Icon name="mdi:gamepad-variant" className="text-site-icon-hover" />}
        {!activity && !spotify && <span className={`h-2 w-2 animate-bounce rounded-full ${statusColor}`} />}
        <span className="font-mono">{title}</span>
      </header>
      {spotify && <section className="flex items-center gap-2 pb-2 text-sm md:block md:px-1 md:p-2">
        <a href={`spotify:track:${spotify.track_id}`} className="flex items-center gap-2 md:block"><span className="block overflow-hidden text-ellipsis whitespace-nowrap font-bold">{spotify.song}</span><span className="block overflow-hidden text-ellipsis whitespace-nowrap">by <span className="font-bold">{spotify.artist}</span></span></a>
        <div className="mt-2 hidden h-2 overflow-hidden rounded-md bg-site-spotify-track md:block"><div className="h-full bg-site-spotify-progress transition-[width] duration-75" style={{ width: `${progress}%` }} /></div>
        <time className="hidden md:block">{minutes}:{seconds}</time>
      </section>}
      {!spotify && activity && <section><span className="font-semibold text-site-heading">{activity.name}</span>{activity.state && <div><span>Currently: </span><span className="font-semibold">{activity.state}</span></div>}</section>}
    </section>
  )
}

// src/components/status-card.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { useLanyard } from 'svelte-lanyard'
	import { fly } from 'svelte/transition'
	import Game from '$components/icons-svelte/game.svelte'
	import Spotify from '$components/icons-svelte/spotify.svelte'

	const UPDATE_TIMESTAMPS_RATE: number = 1000
	const PING_PONG_WEBSOCKET_RATE: number = 300000

	let data: ReturnType<typeof useLanyard>

	let currentTimestamp: number = Date.now()
	let startTimestamp: number = 0
	let endTimestamp: number = 0
	let currentMinutes: number = 0
	let currentSeconds: number = 0
	let clear: ReturnType<typeof setInterval>
	let pingPongWebsocket: ReturnType<typeof setInterval>
	let progress = 0

	onMount(() => {
		data = useLanyard('394953409855488012')
		pingPongWebsocket = setInterval(() => {
			data = useLanyard('394953409855488012')
		}, PING_PONG_WEBSOCKET_RATE)
		clear = setInterval(() => updateTimestamps($data), UPDATE_TIMESTAMPS_RATE)

		return () => {
			clearInterval(clear)
			clearInterval(pingPongWebsocket)
		}
	})

	// For Progress Bar
	function updateTimestamps(spotify_data: typeof $data) {
		if (spotify_data) {
			currentTimestamp = Date.now()
			startTimestamp = spotify_data.spotify?.timestamps.start!
			endTimestamp = spotify_data.spotify?.timestamps.end!
			let totalDuration = endTimestamp - startTimestamp
			let elapsedDuration = currentTimestamp - startTimestamp
			progress = (elapsedDuration / totalDuration) * 100

			let differenceInMilliseconds = currentTimestamp - startTimestamp!
			currentMinutes = Math.floor(differenceInMilliseconds / (1000 * 60)) // Convert milliseconds to minutes

			currentSeconds = Math.floor((differenceInMilliseconds / 1000) % 60)
		}
	}

	function getCurrentTitle(data: typeof $data) {
		if (data && data.listening_to_spotify) {
			return 'Listening to Spotify'
		}

		if (data && data.activities.length >= 1) {
			return 'Playing'
		}

		return 'Thinking...'
	}

	$: formattedSeconds = currentSeconds < 10 ? '0' + currentSeconds : currentSeconds
</script>

<section class="p-1 overflow-hidden">
	<header class="flex items-center gap-2 md:border-b border-b-highlight md:pb-1 md:mb-1 text-sm">
		<span
			class:text-green-500={$data && $data.discord_status === 'online'}
			class:text-yellow-500={$data && $data.discord_status === 'idle'}
			class:text-red-500={($data && $data.discord_status === 'dnd') ||
				($data && $data.discord_status === 'offline')}
		>
			{#if $data && $data.listening_to_spotify}
				<Spotify />
			{/if}

			{#if $data && !$data.listening_to_spotify && $data.activities.length >= 1}
				<Game />
			{/if}
		</span>

		<div
			class="h-2 w-2 rounded-full animate-bounce transition-colors duration-150 ease-linear"
			class:bg-green-500={$data && $data.discord_status === 'online'}
			class:bg-yellow-500={$data && $data.discord_status === 'idle'}
			class:bg-red-500={($data && $data.discord_status === 'dnd') ||
				($data && $data.discord_status === 'offline') ||
				!$data}
			class:hidden={$data && $data.activities.length > 0}
		></div>

		<span class="font-mono">{getCurrentTitle($data)}</span>
	</header>

	{#if $data}
		{#if $data.listening_to_spotify}
			<section
				class="md:p-2 pb-2 md:px-1 text-sm flex md:block items-center gap-2"
				in:fly={{ x: -50, duration: 100 }}
				out:fly={{ x: 50, duration: 100 }}
			>
				<a
					href={`spotify:track:${$data.spotify?.track_id}`}
					class="flex items-center md:block gap-2"
				>
					<span class="block text-ellipsis overflow-hidden whitespace-nowrap font-bold"
						>{$data.spotify?.song}</span
					>
					<span class="block text-ellipsis overflow-hidden whitespace-nowrap"
						>by <span class="font-bold">{$data.spotify?.artist}</span></span
					>
				</a>
				<div
					class="progress-bar h-2 bg-spotify-progress-outer rounded-md overflow-hidden mt-2 hidden md:block"
				>
					<div
						class="bg-spotify-progress h-full w-[--progress] transition-[width] duration-75 ease-linear"
						style={`--progress: ${progress}%`}
					></div>
				</div>
				<time class="hidden md:block">
					{currentMinutes}:{formattedSeconds}
				</time>
			</section>
		{/if}
		{#if !$data.listening_to_spotify && $data.activities.length >= 1}
			<section>
				<span class="font-semibold text-heading">{$data.activities[0].name}</span>
				{#if $data.activities[0].state}
					<div>
						<span>Currently: </span><span class="font-semibold">{$data.activities[0].state}</span>
					</div>
				{/if}
			</section>
		{/if}
	{/if}
</section>
